/* Generated by scripts/build-lexicon.mjs from the seed lists in
 * scripts/lexicon-seeds.mjs. Edit those and re-run; do not edit this.
 *
 * The prefixes a separable verb's particle can be.
 *
 * A TypeScript module rather than the .json it used to be: Node's ESM loader
 * demands an import attribute for JSON and bundlers do not, and a library
 * consumed by both should not make its consumers care about the difference.
 *
 * Typed rather than inferred, and deliberately not `as const`: the literal
 * type of four and a half thousand entries is a declaration file nobody can
 * open, and every reader of these tables wants the wide type anyway. */
const table: string[] = [
"herunter",
"zusammen",
"entgegen",
"herauf",
"herein",
"heraus",
"hinter",
"nieder",
"weiter",
"wieder",
"zurück",
"vorbei",
"unter",
"durch",
"empor",
"davon",
"daran",
"voran",
"fest",
"fort",
"nach",
"über",
"dazu",
"auf",
"aus",
"bei",
"ein",
"her",
"hin",
"los",
"mit",
"vor",
"weg",
"ab",
"an",
"zu",
"um"
];

export default table;
