// Seed lists for the German lexicon. Kept compact and human-editable; the
// generator in build-lexicon.mjs expands these into inflected-form tables.

/** Regular ("weak") verbs. Forms are generated from the stem. */
export const WEAK_VERBS = [
  'machen','sagen','spielen','holen','legen','stellen','setzen','kaufen','zeigen','fragen',
  'lernen','wohnen','arbeiten','warten','baden','reden','öffnen','rechnen','zeichnen','atmen',
  'kochen','backen','putzen','räumen','decken','wischen','kehren','falten','pflegen','hören',
  'schauen','gucken','suchen','brauchen','wünschen','lieben','hassen','danken','grüßen','weinen',
  'lachen','träumen','wecken','klopfen','drücken','malen','basteln','turnen','tanzen','klatschen',
  'winken','teilen','sammeln','ordnen','packen','schenken','feiern','besuchen','erzählen','erklären',
  'antworten','üben','wiederholen','probieren','versuchen','schmecken','fühlen','streicheln','kuscheln','umarmen',
  'küssen','trösten','stören','ärgern','freuen','fürchten','wundern','erschrecken','beruhigen','entschuldigen',
  'bedanken','begrüßen','verabschieden','anziehen','ausziehen','aufräumen','einkaufen','abholen','mitbringen','zumachen',
  'aufmachen','anmachen','ausmachen','kämmen','duschen','föhnen','schminken','rasieren','wiegen','zählen',
  'kleben','schaukeln','rutschen','klettern','hüpfen','rennen','wandern','reisen','parken','bremsen',
  'starten','landen','tauchen','segeln','rudern','angeln','jagen','füttern','tränken','pflanzen',
  'ernten','säen','graben','harken','mähen','schaufeln','streuen','bauen','reparieren','bohren',
  'sägen','hämmern','schrauben','streichen','tapezieren','fegen','lüften','heizen','telefonieren','simsen',
  'tippen','drucken','speichern','löschen','laden','filmen','fotografieren','operieren','impfen','verbinden',
  'heilen','husten','niesen','schwitzen','bluten','zittern','regnen','schneien','hageln','donnern',
  'kämpfen','rühren','schaffen','flüstern','brüllen','schimpfen','loben','erlauben','warnen','beeilen',
  'aufpassen','zuhören','mitmachen','einpacken','auspacken','umziehen','hinsetzen','hinlegen','stolpern','schubsen',
  'klingeln','knüllen','stapeln','sortieren','abtrocknen','abwaschen','einschenken','umrühren','schälen','grillen',
  'rösten','kühlen','wärmen','gähnen','schnarchen','aufwachen','ausruhen','entspannen','radeln','rodeln',
  'planschen','spritzen','melken','pflücken','verstecken','vertragen','zaubern','verwandeln','retten','bewachen',
  'aufhängen',
];

/** Irregular verbs: infinitive -> the forms that matter for lookup. */
export const STRONG_VERBS = {
  'sein': ['bin','bist','ist','sind','seid','war','warst','waren','wart','gewesen','sei','seien','wäre','wären'],
  'haben': ['habe','hast','hat','habt','haben','hatte','hattest','hatten','hattet','gehabt','hätte','hätten'],
  'werden': ['werde','wirst','wird','werdet','werden','wurde','wurdest','wurden','wurdet','geworden','worden','würde','würden'],
  'gehen': ['gehe','gehst','geht','gehen','ging','gingst','gingen','gingt','gegangen','geh'],
  'stehen': ['stehe','stehst','steht','stehen','stand','standen','gestanden','steh'],
  'sehen': ['sehe','siehst','sieht','sehen','sah','sahen','gesehen','sieh','säh'],
  'essen': ['esse','isst','ißt','esst','essen','aß','aßen','gegessen','iss'],
  'trinken': ['trinke','trinkst','trinkt','trinken','trank','tranken','getrunken','trink'],
  'schlafen': ['schlafe','schläfst','schläft','schlafen','schlief','schliefen','geschlafen','schlaf'],
  'laufen': ['laufe','läufst','läuft','laufen','lief','liefen','gelaufen','lauf'],
  'fahren': ['fahre','fährst','fährt','fahren','fuhr','fuhren','gefahren','fahr'],
  'lesen': ['lese','liest','lest','lesen','las','lasen','gelesen','lies'],
  'schreiben': ['schreibe','schreibst','schreibt','schreiben','schrieb','schrieben','geschrieben','schreib'],
  'sprechen': ['spreche','sprichst','spricht','sprechen','sprach','sprachen','gesprochen','sprich'],
  'geben': ['gebe','gibst','gibt','geben','gab','gaben','gegeben','gib'],
  'nehmen': ['nehme','nimmst','nimmt','nehmen','nahm','nahmen','genommen','nimm'],
  'kommen': ['komme','kommst','kommt','kommen','kam','kamen','gekommen','komm'],
  'finden': ['finde','findest','findet','finden','fand','fanden','gefunden','find'],
  'sitzen': ['sitze','sitzt','sitzen','saß','saßen','gesessen','sitz'],
  'liegen': ['liege','liegst','liegt','liegen','lag','lagen','gelegen','lieg'],
  'singen': ['singe','singst','singt','singen','sang','sangen','gesungen','sing'],
  'springen': ['springe','springst','springt','springen','sprang','sprangen','gesprungen','spring'],
  'helfen': ['helfe','hilfst','hilft','helfen','half','halfen','geholfen','hilf'],
  'werfen': ['werfe','wirfst','wirft','werfen','warf','warfen','geworfen','wirf'],
  'fangen': ['fange','fängst','fängt','fangen','fing','fingen','gefangen','fang'],
  'halten': ['halte','hältst','hält','halten','hielt','hielten','gehalten','halt'],
  'fallen': ['falle','fällst','fällt','fallen','fiel','fielen','gefallen','fall'],
  'tragen': ['trage','trägst','trägt','tragen','trug','trugen','getragen','trag'],
  'waschen': ['wasche','wäschst','wäscht','waschen','wusch','wuschen','gewaschen','wasch'],
  'wissen': ['weiß','weißt','wisst','wissen','wusste','wussten','gewusst'],
  'können': ['kann','kannst','könnt','können','konnte','konnten','gekonnt','könnte','könnten'],
  'wollen': ['will','willst','wollt','wollen','wollte','wollten','gewollt'],
  'mögen': ['mag','magst','mögt','mögen','mochte','mochten','gemocht','möchte','möchtest','möchten','möchtet'],
  'müssen': ['muss','muß','musst','müsst','müssen','musste','mussten','gemusst','müsste','müssten'],
  'dürfen': ['darf','darfst','dürft','dürfen','durfte','durften','gedurft','dürfte','dürften'],
  'sollen': ['soll','sollst','sollt','sollen','sollte','sollten','gesollt'],
  'tun': ['tue','tust','tut','tun','tat','taten','getan'],
  'lassen': ['lasse','lässt','lasst','lassen','ließ','ließen','gelassen','lass'],
  'bringen': ['bringe','bringst','bringt','bringen','brachte','brachten','gebracht','bring'],
  'denken': ['denke','denkst','denkt','denken','dachte','dachten','gedacht','denk'],
  'kennen': ['kenne','kennst','kennt','kennen','kannte','kannten','gekannt'],
  'rufen': ['rufe','rufst','ruft','rufen','rief','riefen','gerufen','ruf'],
  'schreien': ['schreie','schreist','schreit','schreien','schrie','schrien','geschrien'],
  'ziehen': ['ziehe','ziehst','zieht','ziehen','zog','zogen','gezogen','zieh'],
  'fliegen': ['fliege','fliegst','fliegt','fliegen','flog','flogen','geflogen','flieg'],
  'schwimmen': ['schwimme','schwimmst','schwimmt','schwimmen','schwamm','schwammen','geschwommen'],
  'wachsen': ['wachse','wächst','wachsen','wuchs','wuchsen','gewachsen'],
  'treffen': ['treffe','triffst','trifft','treffen','traf','trafen','getroffen','triff'],
  'vergessen': ['vergesse','vergisst','vergesst','vergessen','vergaß','vergaßen','vergessen','vergiss'],
  'gefallen': ['gefalle','gefällst','gefällt','gefallen','gefiel','gefielen'],
  'beißen': ['beiße','beißt','beißen','biss','bissen','gebissen'],
  'schneiden': ['schneide','schneidest','schneidet','schneiden','schnitt','schnitten','geschnitten'],
  'streiten': ['streite','streitest','streitet','streiten','stritt','stritten','gestritten'],
  'reiten': ['reite','reitest','reitet','reiten','ritt','ritten','geritten'],
  'schließen': ['schließe','schließt','schließen','schloss','schlossen','geschlossen'],
  'gießen': ['gieße','gießt','gießen','goss','gossen','gegossen'],
  'riechen': ['rieche','riechst','riecht','riechen','roch','rochen','gerochen'],
  'fressen': ['fresse','frisst','frißt','fresst','fressen','fraß','fraßen','gefressen','friss'],
  'heißen': ['heiße','heißt','heißen','hieß','hießen','geheißen'],
  'bleiben': ['bleibe','bleibst','bleibt','bleiben','blieb','blieben','geblieben','bleib'],
  'schlagen': ['schlage','schlägst','schlägt','schlagen','schlug','schlugen','geschlagen','schlag'],
  'treten': ['trete','trittst','tritt','treten','trat','traten','getreten'],
  'stoßen': ['stoße','stößt','stoßen','stieß','stießen','gestoßen'],
  'verstehen': ['verstehe','verstehst','versteht','verstehen','verstand','verstanden'],
  'bekommen': ['bekomme','bekommst','bekommt','bekommen','bekam','bekamen'],
  'gewinnen': ['gewinne','gewinnst','gewinnt','gewinnen','gewann','gewannen','gewonnen'],
  'verlieren': ['verliere','verlierst','verliert','verlieren','verlor','verloren'],
  'brechen': ['breche','brichst','bricht','brechen','brach','brachen','gebrochen'],
  'scheinen': ['scheine','scheinst','scheint','scheinen','schien','schienen','geschienen'],
  'steigen': ['steige','steigst','steigt','steigen','stieg','stiegen','gestiegen'],
  'greifen': ['greife','greifst','greift','greifen','griff','griffen','gegriffen'],
  'stinken': ['stinke','stinkst','stinkt','stinken','stank','stanken','gestunken'],
  'schmelzen': ['schmelze','schmilzt','schmelzen','schmolz','geschmolzen'],
  'anfangen': ['fange an','fängt an','fing an','angefangen'],

  'kriechen': ['krieche','kriechst','kriecht','kriechen','kroch','krochen','gekrochen'],
  'hängen': ['hänge','hängst','hängt','hängen','hing','hingen','gehangen','hängte','gehängt','häng'],
  'reißen': ['reiße','reißt','reißen','riss','rissen','gerissen'],
  'messen': ['messe','misst','messt','messen','maß','maßen','gemessen','miss'],
  'braten': ['brate','brätst','brät','braten','briet','brieten','gebraten'],
  'frieren': ['friere','frierst','friert','frieren','fror','froren','gefroren'],
  'versprechen': ['verspreche','versprichst','verspricht','versprechen','versprach','versprochen'],
  'verbieten': ['verbiete','verbietest','verbietet','verbieten','verbot','verboten'],
  'aufheben': ['hebe auf','hebst auf','hebt auf','hob auf','aufgehoben','aufheben'],
  'aufstehen': ['stehe auf','stehst auf','steht auf','stand auf','aufgestanden','aufstehen'],
  'einschlafen': ['schlafe ein','schläfst ein','schläft ein','schlief ein','eingeschlafen','einschlafen'],
  'vorlesen': ['vorlese','vorliest','vorlest','vorlesen','vorlas','vorlasen','vorgelesen'],
  'wachsen ': [],
};

/** Separable-verb prefixes. Order matters only for display, not matching. */
export const SEPARABLE_PREFIXES = [
  'ab','an','auf','aus','bei','ein','fest','fort','her','herunter','herauf','herein','heraus',
  'hin','hinter','los','mit','nach','nieder','vor','weg','weiter','wieder','zu','zurück','zusammen',
  'um','über','unter','durch','entgegen','empor','dazu','davon','daran','vorbei','voran','vorbei',
];

/** Nouns as [singular, ...plural/other forms]. Singular is the concept key. */
export const NOUNS = [
  ['Apfel','Äpfel','Apfels'],['Banane','Bananen'],['Birne','Birnen'],['Traube','Trauben'],
  ['Erdbeere','Erdbeeren'],['Kirsche','Kirschen'],['Zitrone','Zitronen'],['Orange','Orangen'],
  ['Melone','Melonen'],['Pfirsich','Pfirsiche'],['Pflaume','Pflaumen'],['Ananas'],
  ['Brot','Brote','Brotes'],['Brötchen'],['Butter'],['Käse','Käses'],['Wurst','Würste'],
  ['Ei','Eier','Eies'],['Milch'],['Wasser','Wassers'],['Saft','Säfte','Saftes'],['Tee','Tees'],
  ['Kaffee','Kaffees'],['Kakao'],['Suppe','Suppen'],['Salat','Salate'],['Nudel','Nudeln'],
  ['Reis','Reises'],['Kartoffel','Kartoffeln'],['Gemüse'],['Obst','Obstes'],['Fleisch','Fleisches'],
  ['Fisch','Fische','Fisches'],['Kuchen','Kuchens'],['Keks','Kekse'],['Schokolade','Schokoladen'],
  ['Eis','Eises'],['Bonbon','Bonbons'],['Honig'],['Marmelade','Marmeladen'],['Zucker'],['Salz','Salzes'],
  ['Pizza','Pizzen','Pizzas'],['Pommes'],['Joghurt','Joghurts'],['Müsli','Müslis'],['Tomate','Tomaten'],
  ['Gurke','Gurken'],['Karotte','Karotten'],['Möhre','Möhren'],['Zwiebel','Zwiebeln'],['Paprika'],
  ['Mama','Mamas'],['Papa','Papas'],['Mutter','Mütter'],['Vater','Väter'],['Kind','Kinder','Kindes'],
  ['Junge','Jungen'],['Mädchen'],['Baby','Babys'],['Bruder','Brüder'],['Schwester','Schwestern'],
  ['Oma','Omas'],['Opa','Opas'],['Familie','Familien'],['Freund','Freunde','Freundes'],
  ['Freundin','Freundinnen'],['Mann','Männer','Mannes'],['Frau','Frauen'],['Mensch','Menschen'],
  ['Lehrer','Lehrers'],['Lehrerin','Lehrerinnen'],['Arzt','Ärzte','Arztes'],['Ärztin','Ärztinnen'],
  ['Hund','Hunde','Hundes'],['Katze','Katzen'],['Pferd','Pferde','Pferdes'],['Kuh','Kühe'],
  ['Schwein','Schweine','Schweines'],['Schaf','Schafe','Schafes'],['Ziege','Ziegen'],['Huhn','Hühner'],
  ['Hahn','Hähne'],['Ente','Enten'],['Gans','Gänse'],['Vogel','Vögel','Vogels'],['Maus','Mäuse'],
  ['Hase','Hasen'],['Kaninchen'],['Bär','Bären'],['Löwe','Löwen'],['Elefant','Elefanten'],
  ['Affe','Affen'],['Giraffe','Giraffen'],['Tiger','Tigers'],['Wolf','Wölfe','Wolfes'],
  ['Fuchs','Füchse','Fuchses'],['Igel','Igels'],['Schmetterling','Schmetterlinge'],['Biene','Bienen'],
  ['Spinne','Spinnen'],['Käfer','Käfers'],['Schnecke','Schnecken'],['Frosch','Frösche','Frosches'],
  ['Schlange','Schlangen'],['Tier','Tiere','Tieres'],['Pinguin','Pinguine'],['Delfin','Delfine'],
  ['Haus','Häuser','Hauses'],['Wohnung','Wohnungen'],['Zimmer','Zimmers'],['Küche','Küchen'],
  ['Bad','Bäder','Bades'],['Garten','Gärten','Gartens'],['Tür','Türen'],['Fenster','Fensters'],
  ['Tisch','Tische','Tisches'],['Stuhl','Stühle','Stuhles'],['Bett','Betten','Bettes'],
  ['Sofa','Sofas'],['Schrank','Schränke','Schrankes'],['Lampe','Lampen'],['Teppich','Teppiche'],
  ['Spiegel','Spiegels'],['Regal','Regale'],['Treppe','Treppen'],['Dach','Dächer','Daches'],
  ['Keller','Kellers'],['Boden','Böden','Bodens'],['Wand','Wände'],['Decke','Decken'],
  ['Teller','Tellers'],['Tasse','Tassen'],['Glas','Gläser','Glases'],['Flasche','Flaschen'],
  ['Löffel','Löffels'],['Gabel','Gabeln'],['Messer','Messers'],['Topf','Töpfe','Topfes'],
  ['Pfanne','Pfannen'],['Schüssel','Schüsseln'],['Kanne','Kannen'],['Serviette','Servietten'],
  ['Zahnbürste','Zahnbürsten'],['Handtuch','Handtücher','Handtuches'],['Seife','Seifen'],
  ['Kamm','Kämme','Kammes'],['Bürste','Bürsten'],['Schere','Scheren'],['Windel','Windeln'],
  ['Toilette','Toiletten'],['Dusche','Duschen'],['Badewanne','Badewannen'],['Waschbecken'],
  ['Hose','Hosen'],['Hemd','Hemden','Hemdes'],['Pullover','Pullovers'],['Jacke','Jacken'],
  ['Mantel','Mäntel','Mantels'],['Kleid','Kleider','Kleides'],['Rock','Röcke','Rockes'],
  ['Schuh','Schuhe','Schuhes'],['Socke','Socken'],['Strumpf','Strümpfe'],['Mütze','Mützen'],
  ['Hut','Hüte','Hutes'],['Schal','Schals'],['Handschuh','Handschuhe'],['Gürtel','Gürtels'],
  ['Tasche','Taschen'],['Rucksack','Rucksäcke','Rucksackes'],['Brille','Brillen'],['Uhr','Uhren'],
  ['Ball','Bälle','Balles'],['Puppe','Puppen'],['Auto','Autos'],['Bus','Busse','Busses'],
  ['Zug','Züge','Zuges'],['Fahrrad','Fahrräder','Fahrrades'],['Rad','Räder','Rades'],
  ['Roller','Rollers'],['Schiff','Schiffe','Schiffes'],['Boot','Boote','Bootes'],
  ['Flugzeug','Flugzeuge','Flugzeuges'],['Traktor','Traktoren'],['Bagger','Baggers'],
  ['Motorrad','Motorräder'],['Rollstuhl','Rollstühle'],['Straßenbahn','Straßenbahnen'],
  ['Buch','Bücher','Buches'],['Heft','Hefte','Heftes'],['Stift','Stifte','Stiftes'],
  ['Bleistift','Bleistifte'],['Papier','Papiere','Papieres'],['Schere','Scheren'],
  ['Kleber','Klebers'],['Farbe','Farben'],['Pinsel','Pinsels'],['Tafel','Tafeln'],
  ['Schule','Schulen'],['Kindergarten','Kindergärten'],['Klasse','Klassen'],['Pause','Pausen'],
  ['Aufgabe','Aufgaben'],['Bild','Bilder','Bildes'],['Spiel','Spiele','Spieles'],
  ['Musik'],['Lied','Lieder','Liedes'],['Geschichte','Geschichten'],['Film','Filme','Filmes'],
  ['Baum','Bäume','Baumes'],['Blume','Blumen'],['Blatt','Blätter','Blattes'],['Gras','Gräser'],
  ['Wald','Wälder','Waldes'],['Wiese','Wiesen'],['Berg','Berge','Berges'],['See','Seen','Sees'],
  ['Meer','Meere','Meeres'],['Fluss','Flüsse','Flusses'],['Strand','Strände','Strandes'],
  ['Himmel','Himmels'],['Sonne','Sonnen'],['Mond','Monde','Mondes'],['Stern','Sterne','Sternes'],
  ['Wolke','Wolken'],['Regen','Regens'],['Schnee','Schnees'],['Wind','Winde','Windes'],
  ['Sturm','Stürme'],['Gewitter','Gewitters'],['Nebel','Nebels'],['Eis','Eises'],
  ['Park','Parks'],['Spielplatz','Spielplätze','Spielplatzes'],['Straße','Straßen'],
  ['Weg','Wege','Weges'],['Stadt','Städte'],['Dorf','Dörfer','Dorfes'],['Laden','Läden'],
  ['Geschäft','Geschäfte'],['Markt','Märkte','Marktes'],['Supermarkt','Supermärkte'],
  ['Bäckerei','Bäckereien'],['Apotheke','Apotheken'],['Krankenhaus','Krankenhäuser'],
  ['Kirche','Kirchen'],['Museum','Museen'],['Zoo','Zoos'],['Schwimmbad','Schwimmbäder'],
  ['Bahnhof','Bahnhöfe','Bahnhofes'],['Flughafen','Flughäfen'],['Restaurant','Restaurants'],
  ['Hand','Hände'],['Fuß','Füße','Fußes'],['Kopf','Köpfe','Kopfes'],['Auge','Augen'],
  ['Ohr','Ohren','Ohres'],['Nase','Nasen'],['Mund','Münder','Mundes'],['Zahn','Zähne','Zahnes'],
  ['Haar','Haare','Haares'],['Arm','Arme','Armes'],['Bein','Beine','Beines'],['Bauch','Bäuche'],
  ['Rücken','Rückens'],['Finger','Fingers'],['Zeh','Zehen'],['Knie','Knies'],['Hals','Hälse'],
  ['Herz','Herzen','Herzens'],['Gesicht','Gesichter','Gesichtes'],['Körper','Körpers'],
  ['Tag','Tage','Tages'],['Nacht','Nächte'],['Morgen','Morgens'],['Abend','Abende','Abends'],
  ['Mittag','Mittage'],['Woche','Wochen'],['Monat','Monate','Monates'],['Jahr','Jahre','Jahres'],
  ['Stunde','Stunden'],['Minute','Minuten'],['Zeit','Zeiten'],['Geburtstag','Geburtstage'],
  ['Weihnachten'],['Ostern'],['Ferien'],['Urlaub','Urlaube'],['Geschenk','Geschenke','Geschenkes'],
  ['Angst','Ängste'],['Freude','Freuden'],['Wut'],['Schmerz','Schmerzen','Schmerzes'],
  ['Hunger','Hungers'],['Durst','Durstes'],['Fieber','Fiebers'],['Husten','Hustens'],
  ['Pflaster','Pflasters'],['Medizin','Medizinen'],['Hilfe','Hilfen'],['Frage','Fragen'],
  ['Antwort','Antworten'],['Name','Namen','Namens'],['Geld','Gelder','Geldes'],
  ['Telefon','Telefone','Telefones'],['Handy','Handys'],['Computer','Computers'],
  ['Fernseher','Fernsehers'],['Radio','Radios'],['Schlüssel','Schlüssels'],['Koffer','Koffers'],
  ['Apfelsaft','Apfelsäfte'],['Orangensaft','Orangensäfte'],['Zahnpasta'],['Hausaufgabe','Hausaufgaben'],

  // --- picture books and fairy tales: the material people actually translate ---
  ['Eule','Eulen'],['Ast','Äste','Astes'],['Monster','Monsters'],['Gespenst','Gespenster'],
  ['Prinzessin','Prinzessinnen'],['Prinz','Prinzen'],['König','Könige','Königs'],
  ['Königin','Königinnen'],['Ritter','Ritters'],['Drache','Drachen'],['Hexe','Hexen'],
  ['Zauberer','Zauberers'],['Fee','Feen'],['Riese','Riesen'],['Zwerg','Zwerge'],
  ['Kessel','Kessels'],['Krone','Kronen'],['Schloss','Schlösser','Schlosses'],
  ['Burg','Burgen'],['Höhle','Höhlen'],['Schatz','Schätze','Schatzes'],
  ['Zauberstab','Zauberstäbe'],['Turm','Türme','Turmes'],['Schwert','Schwerter'],
  ['Eichhörnchen'],['Reh','Rehe'],['Hirsch','Hirsche'],['Dachs','Dachse'],['Biber','Bibers'],
  ['Storch','Störche'],['Rabe','Raben'],['Taube','Tauben'],['Möwe','Möwen'],['Wal','Wale'],
  ['Hai','Haie'],['Krebs','Krebse'],['Muschel','Muscheln'],['Qualle','Quallen'],
  ['Krokodil','Krokodile'],['Zebra','Zebras'],['Kamel','Kamele'],['Esel','Esels'],
  ['Papagei','Papageien'],['Schildkröte','Schildkröten'],['Fledermaus','Fledermäuse'],
  ['Maulwurf','Maulwürfe'],['Ameise','Ameisen'],['Wurm','Würmer','Wurmes'],
  ['Raupe','Raupen'],['Marienkäfer','Marienkäfers'],['Nest','Nester'],['Feder','Federn'],
  ['Fell','Felle'],['Pfote','Pfoten'],['Flügel','Flügels'],['Schwanz','Schwänze'],

  // --- school ---
  ['Schulranzen','Schulranzens'],['Schulhof','Schulhöfe'],['Buntstift','Buntstifte'],
  ['Radiergummi','Radiergummis'],['Federmappe','Federmappen'],['Lineal','Lineale'],
  ['Turnhalle','Turnhallen'],['Zeugnis','Zeugnisse'],['Stundenplan','Stundenpläne'],
  ['Klassenzimmer','Klassenzimmers'],['Spitzer','Spitzers'],['Wörterbuch','Wörterbücher'],
  ['Schulbus','Schulbusse'],['Hausaufgaben'],['Ferienbeginn'],

  // --- household ---
  ['Staubsauger','Staubsaugers'],['Wäsche'],['Mülleimer','Mülleimers'],
  ['Schublade','Schubladen'],['Waschmaschine','Waschmaschinen'],
  ['Geschirrspüler','Geschirrspülers'],['Besen','Besens'],['Eimer','Eimers'],
  ['Lappen','Lappens'],['Bügeleisen','Bügeleisens'],['Müll','Mülls'],['Kissen','Kissens'],
  ['Bettdecke','Bettdecken'],['Vorhang','Vorhänge'],['Heizung','Heizungen'],
  ['Steckdose','Steckdosen'],['Kerze','Kerzen'],['Streichholz','Streichhölzer'],
  ['Wäscheleine','Wäscheleinen'],['Schrankfach','Schrankfächer'],

  // --- play ---
  ['Puzzle','Puzzles'],['Kuscheltier','Kuscheltiere'],['Bauklotz','Bauklötze'],
  ['Murmel','Murmeln'],['Schaukel','Schaukeln'],['Rutsche','Rutschen'],
  ['Sandkasten','Sandkästen'],['Teddy','Teddys'],['Knete'],['Würfel','Würfels'],
  ['Brettspiel','Brettspiele'],['Wippe','Wippen'],['Klettergerüst','Klettergerüste'],
  ['Trampolin','Trampoline'],['Versteck','Verstecke'],['Luftballon','Luftballons'],
  ['Seifenblase','Seifenblasen'],['Kreide','Kreiden'],

  // --- feeling and getting along ---
  ['Entschuldigung','Entschuldigungen'],['Versehen','Versehens'],
  ['Glückwunsch','Glückwünsche'],['Überraschung','Überraschungen'],
  ['Geheimnis','Geheimnisse'],['Streit','Streite'],['Freundschaft','Freundschaften'],
  ['Besuch','Besuche'],['Gefühl','Gefühle'],['Laune','Launen'],['Mut','Mutes'],
  ['Sorge','Sorgen'],['Trost','Trostes'],['Kuss','Küsse','Kusses'],
  ['Umarmung','Umarmungen'],['Witz','Witze'],['Träne','Tränen'],['Langeweile'],

  // --- time and weather ---
  ['Wochenende','Wochenenden'],['Winter','Winters'],['Sommer','Sommers'],
  ['Frühling','Frühlinge'],['Herbst','Herbstes'],['Jahreszeit','Jahreszeiten'],
  ['Uhrzeit','Uhrzeiten'],['Feiertag','Feiertage'],['Nachmittag','Nachmittage'],
  ['Vormittag','Vormittage'],['Sekunde','Sekunden'],['Kalender','Kalenders'],
  ['Regenbogen','Regenbögen'],['Blitz','Blitze'],['Donner','Donners'],['Hagel','Hagels'],
  ['Pfütze','Pfützen'],['Schneemann','Schneemänner'],['Schlitten','Schlittens'],
  ['Januar'],['Februar'],['März'],['April'],['Mai'],['Juni'],['Juli'],['August'],
  ['September'],['Oktober'],['November'],['Dezember'],

  // --- body and health ---
  ['Bauchweh'],['Kopfweh'],['Halsweh'],['Zahnweh'],['Schnupfen','Schnupfens'],
  ['Wunde','Wunden'],['Verband','Verbände'],['Spritze','Spritzen'],
  ['Zahnarzt','Zahnärzte'],['Krankenschwester','Krankenschwestern'],
  ['Krankenwagen','Krankenwagens'],['Tablette','Tabletten'],['Thermometer','Thermometers'],
  ['Hörgerät','Hörgeräte'],['Rollator','Rollatoren'],['Therapie','Therapien'],
  ['Schulter','Schultern'],['Ellbogen','Ellbogens'],['Daumen','Daumens'],
  ['Zunge','Zungen'],['Lippe','Lippen'],['Wange','Wangen'],['Stirn','Stirnen'],
  ['Po','Pos'],['Haut','Häute'],

  // --- more food ---
  ['Butterbrot','Butterbrote'],['Pfannkuchen','Pfannkuchens'],['Waffel','Waffeln'],
  ['Sahne'],['Quark'],['Pudding','Puddings'],['Haferflocken'],['Nuss','Nüsse'],
  ['Rosine','Rosinen'],['Erbse','Erbsen'],['Bohne','Bohnen'],['Mais'],['Pilz','Pilze'],
  ['Kürbis','Kürbisse'],['Himbeere','Himbeeren'],['Blaubeere','Blaubeeren'],
  ['Brezel','Brezeln'],['Mehl'],['Teig','Teige'],['Senf'],['Öl','Öle'],

  // --- out and about ---
  ['Haltestelle','Haltestellen'],['Bahnsteig','Bahnsteige'],['Fahrkarte','Fahrkarten'],
  ['Ampel','Ampeln'],['Zebrastreifen','Zebrastreifens'],['Gehweg','Gehwege'],
  ['Brücke','Brücken'],['Tunnel','Tunnels'],['Parkplatz','Parkplätze'],
  ['Tankstelle','Tankstellen'],['Feuerwehr','Feuerwehren'],['Polizei'],['Post'],
  ['Bibliothek','Bibliotheken'],['Kino','Kinos'],['Theater','Theaters'],
  ['Zirkus','Zirkusse'],['Bauernhof','Bauernhöfe'],['Stall','Ställe'],
  ['Scheune','Scheunen'],['Feld','Felder','Feldes'],['Teich','Teiche'],['Bach','Bäche'],
  ['Insel','Inseln'],['Zelt','Zelte'],['Hotel','Hotels'],['Flur','Flure'],
  ['Balkon','Balkone'],['Garage','Garagen'],['Werkstatt','Werkstätten'],
  ['Aufzug','Aufzüge'],['Rolltreppe','Rolltreppen'],['Runde','Runden'],
];

/** Adjectives / adverbs. Base form is the concept key. */
export const ADJECTIVES = [
  'groß','klein','gut','schlecht','schön','hässlich','neu','alt','jung','lang','kurz',
  'hoch','tief','breit','schmal','dick','dünn','schwer','leicht','stark','schwach',
  'schnell','langsam','laut','leise','hell','dunkel','warm','kalt','heiß','kühl',
  'nass','trocken','sauber','schmutzig','voll','leer','offen','geschlossen','hart','weich',
  'süß','sauer','salzig','bitter','scharf','lecker','satt','hungrig','durstig','müde',
  'wach','krank','gesund','fröhlich','traurig','wütend','ängstlich','ruhig','nervös','stolz',
  'lieb','böse','nett','frech','brav','lustig','langweilig','interessant','einfach','schwierig',
  'richtig','falsch','fertig','kaputt','ganz','halb','viel','wenig','mehr','weniger',
  'rot','blau','gelb','grün','schwarz','weiß','braun','grau','rosa','orange','lila','bunt',
  'erste','zweite','dritte','letzte','nächste','glücklich','allein','zusammen','wichtig','fremd',

  'aufgeregt','enttäuscht','eifersüchtig','verlegen','gelangweilt','überrascht','erschrocken',
  'zufrieden','unzufrieden','schläfrig','verletzt','klug','dumm','faul','fleißig','ordentlich',
  'unordentlich','glatt','rau','spitz','rund','eckig','gerade','schief','eng','flach','steil',
  'locker','fest','frisch','reif','roh','lauwarm','eiskalt','herzlich','freundlich',
  'unfreundlich','höflich','gemein','ehrlich','geduldig','ungeduldig','mutig','vorsichtig',
  'gefährlich','sicher','unwichtig','möglich','unmöglich','bereit','früh','spät','pünktlich',
  'ähnlich','verschieden','riesig','winzig','müde','fröhlich',
];

/** Pronouns and other function words that DO deserve a slot in AAC. */
export const KEPT_FUNCTION_WORDS = {
  'ich': ['ich','mich','mir','mein','meine','meinen','meinem','meiner','meines'],
  'du': ['du','dich','dir','dein','deine','deinen','deinem','deiner','deines'],
  'er': ['er','ihn','ihm','sein','seine','seinen','seinem','seiner','seines'],
  'sie': ['sie','ihr','ihre','ihren','ihrem','ihrer','ihres'],
  'es': ['es'],
  'wir': ['wir','uns','unser','unsere','unseren','unserem','unserer'],
  'ihr': ['euch','euer','eure','euren','eurem','eurer'],
  'wer': ['wer','wen','wem','wessen'],
  'was': ['was'],
  'wo': ['wo','wohin','woher'],
  'wann': ['wann'],
  'wie': ['wie'],
  'warum': ['warum','wieso','weshalb'],
  'nicht': ['nicht','nein','kein','keine','keinen','keinem','keiner','keines'],
  'ja': ['ja'],
  'bitte': ['bitte'],
  'danke': ['danke','dankeschön'],
  'hallo': ['hallo','hi','guten tag'],
  'tschüss': ['tschüss','tschüs','auf wiedersehen'],
  'auf': ['auf'], 'unter': ['unter'], 'in': ['in'], 'über': ['über'], 'neben': ['neben'],
  'vor': ['vor'], 'hinter': ['hinter'], 'zwischen': ['zwischen'], 'mit': ['mit'],
  'ohne': ['ohne'], 'für': ['für'], 'gegen': ['gegen'], 'zu': ['zu'], 'von': ['von'],
  'nach': ['nach'], 'aus': ['aus'], 'bei': ['bei'], 'an': ['an'], 'um': ['um'],
  'heute': ['heute'], 'morgen': ['morgen'], 'gestern': ['gestern'], 'jetzt': ['jetzt'],
  'immer': ['immer'], 'nie': ['nie','niemals'], 'oft': ['oft'], 'manchmal': ['manchmal'],
  'hier': ['hier'], 'dort': ['dort','da'], 'oben': ['oben'], 'unten': ['unten'],
  'links': ['links'], 'rechts': ['rechts'], 'und': ['und'], 'oder': ['oder'],
  'aber': ['aber'], 'weil': ['weil'], 'wenn': ['wenn'], 'alle': ['alle','alles'],
  'noch': ['noch'], 'wieder': ['wieder'], 'auch': ['auch'], 'fertig': ['fertig'],
  'Montag': ['montag'], 'Dienstag': ['dienstag'], 'Mittwoch': ['mittwoch'],
  'Donnerstag': ['donnerstag'], 'Freitag': ['freitag'], 'Samstag': ['samstag','sonnabend'],
  'Sonntag': ['sonntag'],

  'durch': ['durch'], 'seit': ['seit'], 'draußen': ['draußen'], 'drinnen': ['drinnen'],
  'vorne': ['vorne','vorn'], 'hinten': ['hinten'], 'überall': ['überall'],
  'weg': ['weg'], 'zurück': ['zurück'], 'weiter': ['weiter'], 'nochmal': ['nochmal','nochmals'],
  'einmal': ['einmal'], 'zweimal': ['zweimal'], 'gleich': ['gleich'], 'sofort': ['sofort'],
  'bald': ['bald'], 'später': ['später'], 'vorher': ['vorher'], 'nachher': ['nachher'],
  'zuerst': ['zuerst'], 'dann': ['dann'], 'endlich': ['endlich'], 'plötzlich': ['plötzlich'],
  'selbst': ['selbst','selber'], 'gern': ['gern','gerne'], 'weh': ['weh'],
  'runter': ['runter','herunter'], 'rauf': ['rauf','herauf'], 'rein': ['rein','herein'],
  'raus': ['raus','heraus'], 'Hause': ['hause'], 'meins': ['meins','deins','seins'],
  'eins': ['eins','ein'], 'zwei': ['zwei'], 'drei': ['drei'], 'vier': ['vier'],
  'fünf': ['fünf'], 'sechs': ['sechs'], 'sieben': ['sieben'], 'acht': ['acht'],
  'neun': ['neun'], 'zehn': ['zehn'], 'elf': ['elf'], 'zwölf': ['zwölf'],
};

/**
 * Default function words that get NO slot of their own. AAC output is telegraphic.
 * Deliberately excludes pronouns, prepositions and modal verbs — those carry meaning.
 * Shipped as data so users can edit the list in the app.
 */
export const STOPWORDS = [
  'der','die','das','den','dem','des','ein','eine','einen','einem','einer','eines',
  'dessen','deren','welche','welcher','welches','welchen','diese','dieser','dieses','diesen','diesem',
  'bin','bist','ist','sind','seid','war','warst','waren','wart','gewesen','sei','seien','wäre','wären',
  'habe','hast','hat','habt','haben','hatte','hattest','hatten','hattet','gehabt','hätte','hätten',
  'werde','wirst','wird','werdet','werden','wurde','wurdest','wurden','wurdet','worden','geworden',
  'dass','daß','ob','denn','doch','mal','halt','eben','wohl','etwa','schon','nur','sehr','so',
  'sich','einander','man','etwas','irgendwie','eigentlich','vielleicht','ziemlich','ganz',
];

/** Synonym groups. Every member resolves to every other member as a fallback. */
export const SYNONYM_GROUPS = [
  ['Fahrrad','Rad','Velo','Bike'],
  ['Auto','Wagen','PKW'],
  ['Kartoffel','Erdapfel'],
  ['Möhre','Karotte','Mohrrübe','Rübli'],
  ['Brötchen','Semmel','Schrippe','Weckle'],
  ['Junge','Bub','Knabe'],
  ['Mädchen','Mädel'],
  ['Mama','Mutter','Mutti'],
  ['Papa','Vater','Vati'],
  ['Oma','Großmutter'],
  ['Opa','Großvater'],
  ['Hund','Hündchen','Welpe'],
  ['Katze','Kätzchen','Mieze'],
  ['Sofa','Couch'],
  ['Handy','Mobiltelefon','Smartphone'],
  ['Fernseher','Fernsehgerät','TV'],
  ['Toilette','Klo','WC'],
  ['Fahrstuhl','Aufzug','Lift'],
  ['Arzt','Doktor','Mediziner'],
  ['Krankenhaus','Klinik'],
  ['Supermarkt','Laden','Geschäft','Markt'],
  ['Bonbon','Süßigkeit','Naschzeug'],
  ['Schokolade','Schoki'],
  ['Getränk','Trinken'],
  ['Jacke','Anorak'],
  ['Mütze','Kappe'],
  ['Pullover','Pulli'],
  ['Hose','Buxe'],
  ['sprechen','reden','sagen'],
  ['gehen','laufen'],
  ['rennen','sprinten'],
  ['schauen','gucken','sehen','blicken'],
  ['essen','speisen'],
  ['fröhlich','glücklich','froh'],
  ['traurig','betrübt'],
  ['wütend','böse','sauer','zornig'],
  ['müde','schläfrig'],
  ['schön','hübsch'],
  ['groß','riesig'],
  ['klein','winzig'],
  ['schnell','flink','rasch'],
  ['kaputt','defekt'],
  ['lecker','köstlich','schmackhaft'],
  ['Spielplatz','Spielpark'],
  ['Kindergarten','Kita'],
  ['Geld','Money','Kohle'],
  ['helfen','unterstützen'],
  ['aufräumen','ordnen','wegräumen'],
  ['tschüss','ciao'],

  ['Bauklotz','Baustein','Klotz'],
  ['Mülleimer','Abfalleimer','Papierkorb'],
  ['Haltestelle','Bushaltestelle','Station'],
  ['Bauchweh','Bauchschmerzen'],
  ['Kopfweh','Kopfschmerzen'],
  ['Wochenende','Samstag','Sonntag'],
  ['Entschuldigung','Verzeihung'],
  ['Glückwunsch','Gratulation'],
  ['Monster','Ungeheuer'],
  ['Gespenst','Geist'],
  ['Schloss','Burg','Palast'],
  ['rennen','laufen','sprinten'],
  ['brüllen','schreien','rufen'],
  ['flüstern','wispern'],
  ['Pfannkuchen','Eierkuchen','Crêpe'],
  ['Brezel','Breze'],
  ['Schulranzen','Tasche','Ranzen','Schultasche'],
  ['Buntstift','Stift','Malstift'],
  ['Streit','streiten','Konflikt','Ärger'],
  ['enttäuscht','traurig'],
  ['höflich','nett','freundlich'],
  ['pünktlich','Zeit','Uhr','rechtzeitig'],
  ['Kuscheltier','Teddy','Stofftier','Puppe'],
  ['aufgeregt','nervös','Aufregung'],
];
